/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'momamene' at '3/8/14 3:03 PM' with Gradle 1.10
 *
 * @author momamene, @date 3/8/14 3:03 PM
 */
import org.chasen.mecab.MeCab;
import org.chasen.mecab.Tagger;
import org.chasen.mecab.Model;
import org.chasen.mecab.Lattice;
import org.chasen.mecab.Node;

public class Library {
    static {
        try {
            System.loadLibrary("MeCab");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Cannot load the example native code.\nMake sure your LD_LIBRARY_PATH contains \'.\'\n" + e);
            System.exit(1);
        }
    }
    public String getMeCabVERSION() {
        return MeCab.VERSION;
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
