/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'momamene' at '3/8/14 3:03 PM' with Gradle 1.10
 *
 * @author momamene, @date 3/8/14 3:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
