import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'momamene' at '3/8/14 3:03 PM' with Gradle 1.10
 *
 * @author momamene, @date 3/8/14 3:03 PM
 */
public class LibraryTest {
    @Test public void testGetMeCabVERSION() {
        Library classUnderTest = new Library();
        assertEquals("0.996", classUnderTest.getMeCabVERSION());
    }
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
